### ISSUE TITLE
Some suggestions 

### ISSUE THREAD

**Issue by ghost** [kig/DataStream.js#13]
Hello kig,

First of all, I would like to say that DataStream is a fundamental piece of software, a must ! Many, many thanks to you and for all your works (HTML5 Rocks !). From our point of view, we should say 
the approach you have choosen is the best one.
We plan to use _DataStream_ for validating upload of files in a production environment, and, maybe, for creating efficient storage of datas. But, we nead a little help.
1. `testTypeArray` routine : line 232 throws an error :
   `var arr = new this[t+"Array"](ds.byteLength/elen);`
   should be (perhaps) 
   `var arr = new this[t+"Array"]( Math.floor(ds.byteLength/elen) );`
2. Map tests fails (never executed)
   in line 136 :
   `if (ds.byteOffset & rarr.BYTES_PER_ELEMENT === 0) {...}`
   the testing value is always false and inside routines is never executed.

Furthermore, I can't understand why you perform a `this._realloc(len * N);`
at the beginning of all the map functions : in my eyes they are not really necessary.

Besides 'seek' and 'isEo' api's, you could add at no charge :
- a 'skip' `function (saut){return this.seek(this.position+saut);},`
  and 
- a 'where' `function (){return this.position;}` ("where".length=5 chars ! - sorry)

Best regards and thank you for the time that you will devote ourselves

**Comment by martianmartian** [comment]
the author was murdered after the last commit was submitted, so nothing posted here will be noticed.(joking)

**Comment by kig** [comment]
The support contract for this project has ended. (joking)

**Comment by kig** [comment]
Jokes aside, thanks for the bug report (even if 2 years late), I'll see if I can remember my way around the codebase well enough to fix things :)

**Comment by kig** [comment]
@numero6fromthevillage 

Regarding skip() and where():
- where() I'd skip since it's 7 characters and turns a property access into a function call. And it's not immediately clear what it is talking about.
- skip() might be good. I used this.position += 4; to do skipping, but that's a bit dirty. skip() would give bounds checking. There's the danger of overengineering it by writing all the variants like skipf32, skipuint32 etc.

_realloc tests if the mapped array is large enough. If yes, it returns right away. If no, it reallocates a larger array.

For the test issues, do you have a script that reproduces the errors? Or how do I repro them?

**Comment by ghost** [comment]
**zombies talk to zombies** ...

I did not know that computers could lead to assassination :
Happy to know you alive and thanks for your messages !


Regarding skip() and where() -- or from() -- :
it's just a matter of style that is of little importance ;
it makes the source more 'educational' and more readable, easier to understand.

- API' where() or from() is absurd simplicity,
but avoids the beginner to ask too much question (laziness is common),

- API' skip(step) is also very simple !
  I think there is no danger of overengineering because no need of variants if we pass a variable 'step' which represents the amount to skip.

Ultimately : few things, , if not coquetry ! 

Concerning _realloc test, I understand today what caused our confusion two years ago :

1. the test is only needed if we proceed to a 'write' operation (WE don't !).
2. Maps functions are systematically called after each Write functions ; result : the test is sometimes called twice.

Once again this is of little importance.

Our 7.000 customers deposit a million documents each year on our platform (about as much as Google customers in **one second** !).
Our goal was to validate the filing of these documents before they are uploaded to the server 
: healthy concern that our prescriber has not yet funded ! Too bad for him.


Unfortunately we are not really able to find the test scripts developed at the time.
I maintain my point of view : the approach you have choosen is the best one,
although we were only concerned with a very part of the features you offer


Today we develop an innovative document architecture/webapps separating html code/javascript code 
and user data in a single file that can be used locally and remotely (favoring the client more than the server).

Thank you so much. A pleasure to be able to discuss a little with you. 
Give yourself emotions of ... assassination and good health

jf.caretteATt2net.fr
