### ISSUE TITLE
CSP (Content Security Policy) throws error

### ISSUE THREAD

**Issue by sivaprabug** [kig/DataStream.js#17]
Hi,

In CSP evaluation throws error()

![image](https://user-images.githubusercontent.com/2444608/55145977-c29d1080-5169-11e9-8b83-303ceed27cc1.png)

regards,
@gsivaprabu

**Comment by kig** [comment]
The CSP errors relate to inline stylesheets, nothing to do with DataStream.js as far as I can tell.
